# your domain
domain: liuxing.sh1.k9s.run
port: 80               # default 12580

# source list file
source-files:
  # use local file
#  - ./source.yaml
#  - ./config/source.yaml
  # use web file
#  - https://raw.githubusercontent.com/liuxingyx/proxypool/master/config/source.yaml
  - https://raw.githubusercontent.com/money-fly/proxypool/master/config/source.yaml
#  - https://raw.githubusercontent.com/Alex950808/proxypool038/master/config/source.yaml
#  - https://raw.githubusercontent.com/wishcaiji/proxypool/master/config/source.yaml
#  - https://raw.githubusercontent.com/grxp/proxypool/master/config/source.yaml

# ======= 可选项，留空使用default值  =======

# postgresql database info
database_url: ""

# interval between each crawling
crawl-interval: 60    # v0.5.x default 15 (minutes)
crontime:             # v0.4.x default 60 (minutes). Deprecated in the newest version
healthcheck-timeout:  # default 5 (seconds)

# speed test
speedtest: false      # default false. Warning: this will consume large network resources.
speedtest-interval:   # default 720 (min)
speed-timeout:        # default 10 (seconds).
connection:           # default 5. The number of speed test connections simultaneously
## active proxy speed test
active-interval:      # default 60 (min)
active-frequency:     # default 100 (requests per interval)
active-max-number:    # default 100. If more than this number of active proxies, the extra will be deprecated by speed

# cloudflare api
cf_email: ""
cf_key: ""
